### ISSUE TITLE
Minor corrections

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/sorting-algorithms-introduction#6]
1. In the first paragraph, second sentence, delete the 'have' found between 'recommendations' and 'should'. After this deletion the sentence should read as follows:  `For example, if you have a recommendation system like Netflix, these recommendations should be delivered in the correct order.`

2. In the second sample showing the variable for `unsortedArray`, add comma between the 6 and -1 to ensure proper differentiation between elements. 
`let unsortedArray = [5, 6, -1, 1, 3]`

**Comment by rrcobb** [comment]
Closed by #7
